import {API_KEY,AUTH_DOMAIN,PROJECT_ID,STORAGE_BUSKET,MESSAGING_SENDER_ID,APP_ID,MEASUREMENT_ID} from '@env'

export default{
    API_KEY,
    AUTH_DOMAIN,
    PROJECT_ID,
    STORAGE_BUSKET,
    MESSAGING_SENDER_ID,
    APP_ID,
    MEASUREMENT_ID
}